name = "ai-llama-forwarder"
compatibility_date = "2023-09-20"
main = "src/index.tsx"

[ai]
binding = "AI"

[vars]
DEFAULT_AI_MODEL = "@cf/meta/llama-3-8b-instruct"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
