name = "ai-llama-forwarder"
compatibility_date = "2023-09-20"
main = "src/index.tsx"

[ai]
binding = "AI"

# Define variables at the top level (for all environments)
vars = { DEFAULT_AI_MODEL = "@cf/meta/llama-3-8b-instruct" }

# OR define it under a specific environment
[env.production]
vars = { DEFAULT_AI_MODEL = "@cf/meta/llama-3-8b-instruct" }
